owner: wasanx25
repos:
  - goss
  - sreq
branch_protections:
  - name: "master"
    protection_request:
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_pull_request_reviews:
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        required_approving_review_count: 1
        dismissal_restrictions:
#          users: []
#          teams: []
      restrictions:
#        users: []
#        teams: []
